site:
  title: Data Sync
  url: 
  start_page: docs::index
content:
  sources:
    - url: .
      branches: HEAD       
ui:
  bundle:
    url: https://github.com/integr8ly/user-docs-site/raw/master/ui-bundle.zip
    snapshot: true
